### ISSUE TITLE
TypeError: Cannot read property 'test' of undefined

### ISSUE THREAD

**Issue by lencioni** [oyslin/replace-in-file-webpack-plugin#3]
I tried setting up this plugin, but didn't specify a `test` or a `files` option, since they are documented as optional and I want it to run on every file. However, I get the following error:

```
/path/to/project/node_modules/replace-in-file-webpack-plugin/index.js:61
                                              return test.test(file);
                                                          ^

TypeError: Cannot read property 'test' of undefined
```

It looks like we probably need to have another branch in the conditional for this case.

**Comment by oyslin** [comment]
Fixed in version 1.0.6. Please install the latest version and test it.
