### ISSUE TITLE
Only replaces a single instance of the found string?

### ISSUE THREAD

**Issue by Friksel** [oyslin/replace-in-file-webpack-plugin#4]
Hi, I like to use this plugin to replace a string by a webpack hash-string. But for some reason the plugin only replaces the first occurance of the searchstring. I'm not sure whether this a setting I'm missing, I'm doing something wrong, or something else. Is there a setting to find and replace all occurancies?

btw, I know html-webpack-plugin can insert hashes, but I'm using a template for a Silverstripe CMS and webpack doesn't like the template-codes in it that much, so that's why I'm trying to find other ways to insert the hash in the template.

Thanks

**Comment by n1313** [comment]
This plugin does global replacement for me. Are you using a regex with global modifier (`/g`)?

**Comment by Friksel** [comment]
Thanks for your response. Ah nice, I didn't try regular expressions with the global modifier yet. This works fine indeed!
